---
- hosts: server2.abc.com
  remote_user: test
  become: yes
  tasks:
  - name: Install nginx
    yum: name=nginx state=installed
  - name: Copy index.html
    copy: src=index.html dest=/usr/share/nginx/html
  - name: Start service
    service: name=nginx state=started

